### ISSUE TITLE
Draft Box Unchecked at initial term submission

### ISSUE THREAD

**Issue by sm4522** [metadata-research/yamz#122]
YAMZ throws a "Not Found" message if a user tries to submit a term with the draft box unchecked. It does not save any information.

**Comment by machawk1** [comment]
I can confirm based on the current yamz.net. The term does not appear in my term list.

**Comment by cr625** [comment]
Should work now. Need to commit db session first before adding Draft tag.

**Comment by machawk1** [comment]
@cr625 I just tried to create a term on yamz.net and still receive the Not Found message when the Draft tag is unchecked. Has the update code been deployed to yamz.net?

**Comment by cr625** [comment]
I don't think yet @jkunze handles the deployment.
